language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install -r requirements.txt --use-mirrors
  - python setup.py develop
# command to run tests
script: py.test py.test --cov w20e.forms --doctest-glob='*.txt' --cov w20e.forms
